name: dump
description: Dumps any objects to structures of maps, lists, and scalars using mirrors.
repository: https://github.com/alexeyinkin/dart-dump
version: 0.1.6

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  test: ^1.22.2
  total_lints: ^3.1.0
